title:            "Hacking is Fun!"
description:      "A collection of my favorite tips and tricks."
logo:             logo.png
url:        	    https://stevemcilwain.github.io

# Owner/author information
owner:
  name:           Steve Mcilwain
  avatar:         logo.png
  email:          
  description:    DEFINITELY A HUMAN
  twitter:        steve_mcilwain
  github:         stevemcilwain
  linkedin:       stevemcilwain      
  
# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: HOME
    url: /
    external: false
    icon: home
  - title: FEATURED
    url: /featured
  - title: CATEGORIES
    url: /categories
  - title: ABOUT
    url: /steve

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  input: GFM
  syntax_highlighter: rouge

prose:
  rooturl: '_posts'
  siteurl: 'https://stevemcilwain.github.io/'
  relativeLinks: 'https://stevemcilwain.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "false"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "add a headline"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "post description"
      - name: "headline"
        field:
          element: "text"
          label: "Headline"
          placeholder: "post headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: 
          options:
            - name: "Personal"
              value: personal
            - name: "Hacking"
              value: hacking
            - name: "Tools"
              value: tools
            - name: "Linux"
              value: linux
            - name: "Windows"
              value: windows
            - name: "Random"
              value: random
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
